[workspace]
authors = ["jamisonpeebles <jamisonpeebles@live.com>"]
channels = ["conda-forge"]
name = "MonteCarloIntegration"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.2,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"
python-dateutil = ">=2.9.0.post0,<3"
scipy = ">=1.17.0,<2"
