[workspace]
authors = ["jamisonpeebles <jamisonpeebles@live.com>"]
channels = ["conda-forge"]
name = "MonteCarloIntegration"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.2,<3"
